before_script:
- git config --global user.email "e@alanev.ru"
- git config --global user.name "eugeneAlanev"
- git remote rm origin
- git remote add origin https://eugeneAlanev:${GH_TOKEN}@github.com/chromolab/chromolab-ui.git
script: npm run travis
env:
  global:
  - secure: cnGpuBQZYy7v0naEHsNSyaOrwMCgwHEOe66Zsrnql+e8SxditRpH2gDBk7rHRRzT9MXNYdDQ9hENJ48CrqCkyo4K9chHVPaXxjSZ752xb4XolBEjpyyjdIUC0GNfxxXKa6EaR4GVeon4kzaI/ViUrSGD6CU3HnkN+aVF8HJGc86kU/i+rixeMZmV83BEEf/7lsCFLZRi/rZxlYq30I1S3BVAnxYofoYFJooEPgaCHxUXMSSa9jUSOZ69ROqhcJe/o7Sf/Q33UMuSo8oZuGtvzUHKEXt9dOGbNC9qj0eo9vjlrq+h/7N5FxnzHd+2rmvyeTczHD2CHaWP+hTw6gQkgIiX07pBq5T7zGjRBkVh+frWFOEuarnehcc4N3J8IWEQGWgm21ktQuPn/XVdJlh6zLsKXCQLuLS16so/ul1412kiwdq4UALz9b6LEFaAnE67eHdnZIE83Q9x2sAcnhdqRG+Lp12ltcEV94aVR6huc1OoSVjuNUiAgtHjipKAZIcOkSid7rqzxQOvzCMMBOBxe5WNmIH26UcbpjeG7lSrhnIZRTQcgzhF84zxZo8z0ufiItK7mkZGDiCNU43lxv7T5v1QHHxIKdj3GvFtWOPOTzClyzouaEx5FdwHoD5XhFyg4hckz20HXCqk9+ZRrNHwbRqVa2gBk6EndTTvoVs7Leo=
language: node_js
node_js:
- '6'
