before_script:
- git config --global user.email "e@alanev.ru"
- git config --global user.name "eugeneAlanev"
- git remote rm origin
- git remote add origin https://eugeneAlanev:${GH_TOKEN}@github.com/chromolab/chromolab-ui.git
script: npm run test
language: node_js
node_js:
- '6'
